#pragma once

//描画順はここで調整可能
enum ACTOR_ID{
	BEGIN_ACTOR,
	STAGE_ACTOR,
	PLATE_ACTOR,
	FOG_ACTOR,

	RESPAWNPOINT_ACTOR,
	PARTICLE_ACTOR,
	PLAYER_ACTOR,
	CAMERA_ACTOR,

	DEAD_BULLET_ACTOR,
	PLAYER_BULLET_ACTOR,
	PLAYER_BULLET_SHOT_ACTOR,
	PLAYER_TARGET_ACTOR,


	SNIPER_LINE_ACTOR,

	MANAGER_ACTOR,

	TREE_ACTOR,


	POOL_ACTOR,
	STAGELINE_ACTOR,


	END_ACTOR
};

enum COL_ID{
	BEGIN_COL,
	PLATE_BULLET_COL,
	PLATE_PLAYER_COL,
	PLATE_GUNRAY_COL,
	PLAYER_TREE_COL,
	PLAYERBULLET_PLAYER_COL,
	PLAYER_GUNLINE_COL,
	BULLET_RESPAENPOINT_COL,
	BULLET_TREE_COL,
	CAMERARAY_PLATE_COL,
	CAMERA_PLATE_COL,
	PLAYER_SNIPERLINE_COL,
	SNIPERLINE_PLATE_COL,
	PLAYER_STAGELINE_COL,
	END_COL
};

enum SPRITE_ID{
	BEGIN_SPRITE,
	CHANGE_SCENE_PARTICLE_SPRITE,

	GAME_FRAME2_SPRITE,
	GAME_FRAME3_SPRITE,
	GAME_FRAME4_SPRITE,
	TARGET_SPRITE,
	SNEPER_SPRITE,
	ATTACK_GAUGE_IN_SPRITE,
	ATTACK_GAUGE_OUT_SPRITE,
	SUUZI_SPRITE,
	SHOT_UI_SPRITE,
	MACHINE_UI_SPRITE,
	SNEPER_UI_SPRITE,
	PLAYER1_MODEL_SPRITE,
	PLAYER2_MODEL_SPRITE,
	PLAYER3_MODEL_SPRITE,
	PLAYER4_MODEL_SPRITE,
	DAMAGE_BACK_SPRITE,
	SINDA_SPRITE,
	SINUYO_SPRITE,
	TEST_SPRITE,

	KEKKA1_SPRITE,
	KEKKA2_SPRITE,
	KEKKA3_SPRITE,
	KEKKA4_SPRITE,

	TROPHY_SPRITE,

	PLAYER1_KAO_E,
	PLAYER2_KAO_E,
	PLAYER3_KAO_E,
	PLAYER4_KAO_E,

	PLAYER1_KAO_M,
	PLAYER2_KAO_M,
	PLAYER3_KAO_M,
	PLAYER4_KAO_M,

	//エフェクト
	KEMURI_1_SPRITE,
	KEMURI_2_SPRITE,
	KEMURI_3_SPRITE,


	SOKOMADE_FONT_SPRITE,
	HIKIWAKE_FONT_SPRITE,
	YO_I_FONT_SPRITE,
	DON_SPRITE,
	OVER_HERT_SPRITE,
	OVER_HERT_FONT_SPRITE,

	//セレクトシーン
	TEX_BACK_SPRITE,
	UP_NINZU_SPRITE,
	UP_RAUND_SPRITE,
	SELECT_BACK_SPRITE,
	SELECT_CURSOR_SPRITE,

	//リザルト
	WIN_PLAYER_SPRITE,
	PLEASE_BUTTON_SPRITE,
	//シーン遷移時の画像
	SCENE_CHANGE_NEXT_RAUND_SPRITE,
	SCENE_CHANGE_TITLE_SPRITE,
	SCENE_CHANGE_GAME_PLAY_SPRITE,
	SCENE_CHANGE_STAGE_SELECT_SPRITE,
	SCENE_CHANGE_RESULT_SPRITE,

	END_SPRITE
};

enum MODEL_ID{
	BEGIN_MODEL,
	SKY_DEMO_MODEL,
	PLAYER1_MODEL,
	PLAYER2_MODEL,
	PLAYER3_MODEL,
	PLAYER4_MODEL,
	DEFAULT_PLATE_MODEL,
	PLAYER_BULLET_MODEL,
	TEST_MODEL,
	RESPAWNPOINT01_MODEL,
	RESPAWNPOINT02_MODEL,
	RESPAWNPOINT03_MODEL,
	RESPAWNPOINT04_MODEL,
	TREE_MODEL,
	TEST_PLAYER_MODEL,
	TEST2_PLAYER_MODEL,
	PARTICLE_MODEL,
	STAGE01_MODEL,
	LINE_MODEL,
	POOL_MODEL,
	NOBREAKPLATE_MODEL,
	RUN_STAGE_MODEL,
	GAME_MASTER_MODEL,
	DAI_MODEL,
	KANKYAKU_1_MODEL,
	KANKYAKU_2_MODEL,
	KANKYAKU_3_MODEL,
	KANKYAKU_4_MODEL,
	KANKYAKU_5_MODEL,
	END_MODEL,
};

enum BGM_ID{
	BEGIN_BGM,

	END_BGM
};

enum SE_ID{
	BEGIN_SE,

	END_SE
};

enum UI_ID{
	// 下層ほど手前に描画
	BEGIN_UI,
	DAMAGE_BACK_UI,
	SELECT_BACK_UI,
	GAMEFRAME_UI,
	TARGET_UI,
	GAUGE_UI,
	DAMAGE_NUM_UI,
	GUN_UI,
	OVER_HERT_UI,
	PARTICLE_UI,
	GAMETIMER_UI,
	RESULT_UI,
	CHANGE_BLOK_UI,
	FONT_UI,
	TEX_BACK_UI,
	END_RESULT_UI,


	SELECT_UI,
	END_UI
};

enum PLAYER_NUMBER {
	PLAYER_NULL,
	PLAYER_1,
	PLAYER_2,
	PLAYER_3,
	PLAYER_4
};

enum ANIMATION {
	NULL_ANIM=999,
	PLAYER_IDLE_ANIM=0,
	PLAYER_RUN1_ANIM,
	PLAYER_RUN2_ANIM,
	PLAYER_JUMP_ANIM,
	PLAYER_BUKI_IDLE_ANIM,
	PLAYER_BUKI_YOKO1_ANIM,
	PLAYER_BUKI_YOKO2_ANIM,
	PLAYER_BUKI_WALK_ANIM,
	PLAYER_BUKI_RUN_ANIM,
	PLAYER_BUKI_JUMP_ANIM,
	PLAYER_DEAD,
	PLAYER_INORI,
	PLAYER_SUPORT,
	PLAYER_WIN1,
	PLAYER_WIN2,
	//観客アニメーション
	KANKYAKU_OUEN_ANIM=0,
	KANKYAKU_MIRU_1_ANIM,
	KANKYAKU_MIRU_2_ANIM,
	KANKYAKU_DANCE_ANIM,
	KANKYAKU_HAND_ANIM,
	//ゲームマスターアニメーション
	GAMEMASTER_HAND_ANIM=0,
	GAMEMASTER_DNACE_1_ANIM,
	GAMEMASTER_DANCE_2_ANIM
};

enum TEXT_FILE_ID {
	GAMEMASTER_TXT
};