#pragma once

//ï`âÊèáÇÕÇ±Ç±Ç≈í≤êÆâ¬î\
enum ACTOR_ID{
	BEGIN_ACTOR,

	STAGE_ACTOR,
	FOG_ACTOR,

	RESPAWNPOINT_ACTOR,
	PLAYER_ACTOR,
	CAMERA_ACTOR,

	DEAD_BULLET_ACTOR,
	PLAYER_BULLET_ACTOR,
	PLAYER_BULLET_SHOT_ACTOR,
	PLAYER_TARGET_ACTOR,
	PLATE_ACTOR,
	SNIPER_LINE_ACTOR,

	MANAGER_ACTOR,

	TREE_ACTOR,

	PARTICLE_ACTOR,
	POOL_ACTOR,
	STAGELINE_ACTOR,


	END_ACTOR
};

enum COL_ID{
	BEGIN_COL,
	PLATE_BULLET_COL,
	PLATE_PLAYER_COL,
	PLATE_GUNRAY_COL,
	PLAYER_TREE_COL,
	PLAYERBULLET_PLAYER_COL,
	PLAYER_GUNLINE_COL,
	BULLET_RESPAENPOINT_COL,
	BULLET_TREE_COL,
	CAMERARAY_PLATE_COL,
	CAMERA_PLATE_COL,
	PLAYER_SNIPERLINE_COL,
	SNIPERLINE_PLATE_COL,
	PLAYER_STAGELINE_COL,
	END_COL
};

enum SPRITE_ID{
	BEGIN_SPRITE,
	CHANGE_SCENE_PARTICLE_SPRITE,

	GAME_FRAME_SPRITE,
	TARGET_SPRITE,
	SNEPER_SPRITE,
	ATTACK_GAUGE_IN_SPRITE,
	ATTACK_GAUGE_OUT_SPRITE,
	SUUZI_SPRITE,
	SHOT_UI_SPRITE,
	MACHINE_UI_SPRITE,
	SNEPER_UI_SPRITE,
	PLAYER1_MODEL_SPRITE,
	PLAYER2_MODEL_SPRITE,
	PLAYER3_MODEL_SPRITE,
	PLAYER4_MODEL_SPRITE,
	DAMAGE_BACK_SPRITE,
	SINDA_SPRITE,
	SINUYO_SPRITE,
	TEST_SPRITE,
	KEKKA_SPRITE,
	TROPHY_SPRITE,

	PLAYER1_KAO_E,
	PLAYER2_KAO_E,
	PLAYER3_KAO_E,
	PLAYER4_KAO_E,

	PLAYER1_KAO_M,
	PLAYER2_KAO_M,
	PLAYER3_KAO_M,
	PLAYER4_KAO_M,
	END_SPRITE
};

enum MODEL_ID{
	BEGIN_MODEL,
	SKY_DEMO_MODEL,
	PLAYER1_MODEL,
	PLAYER2_MODEL,
	PLAYER3_MODEL,
	PLAYER4_MODEL,
	DEFAULT_PLATE_MODEL,
	PLAYER_BULLET_MODEL,
	TEST_MODEL,
	RESPAWNPOINT01_MODEL,
	RESPAWNPOINT02_MODEL,
	RESPAWNPOINT03_MODEL,
	RESPAWNPOINT04_MODEL,
	TREE_MODEL,
	TEST_PLAYER_MODEL,
	TEST2_PLAYER_MODEL,
	PARTICLE_MODEL,
	STAGE01_MODEL,
	LINE_MODEL,
	POOL_MODEL,
	NOBREAKPLATE_MODEL,
	END_MODEL,
};

enum BGM_ID{
	BEGIN_BGM,

	END_BGM
};

enum SE_ID{
	BEGIN_SE,

	END_SE
};

enum UI_ID{
	// â∫ëwÇŸÇ«éËëOÇ…ï`âÊ
	BEGIN_UI,
	DAMAGE_BACK_UI,
	GAMEFRAME_UI,
	TARGET_UI,
	GAUGE_UI,
	DAMAGE_NUM_UI,
	GUN_UI,
	PARTICLE_UI,
	GAMETIMER_UI,
	RESULT_UI,
	CHANGE_BLOK_UI,
	END_UI
};

enum PLAYER_NUMBER {
	PLAYER_NULL,
	PLAYER_1,
	PLAYER_2,
	PLAYER_3,
	PLAYER_4
};

enum ANIMATION {
	NULL_ANIM=999,
	PLAYER_IDLE_ANIM=0,
	PLAYER_WALK_ANIM,
	PLAYER_RUN_ANIM,
	PLAYER_BUKI_IDLE_ANIM,
	PLAYER_BUKI_RUN_ANIM,
	PLAYER_BUKI_YOKO_ANIM,
	PLAYER_BUKI_JUMP_ANIM,
	PLAYER_BUKI_RUNJUMP_ANIM
};